### ISSUE TITLE
Compile error after PR #4885

### ISSUE THREAD

**Issue by Err0r1** [azerothcore/mod-account-mounts#5]
`/home/azerothcore/source/modules/mod-account-mounts/src/mod_account_mount.cpp:21:20: fatal error:
      conversion from 'ObjectGuid' to 'uint32' (aka 'unsigned int') is ambiguous
            uint32 playerGUID = pPlayer->GetGUID();
                   ^            ~~~~~~~~~~~~~~~~~~
/home/azerothcore/source/src/server/game/Entities/Object/ObjectGuid.h:195:9: note: candidate
      function
        operator bool() const { return !IsEmpty(); }
        ^
/home/azerothcore/source/src/server/game/Entities/Object/ObjectGuid.h:239:9: note: candidate
      function has been explicitly deleted
        operator int64() const = delete;
        ^
1 error generated.
`

**Comment by svenbledt** [comment]
Same to mee

**Comment by rhinjard** [comment]
+1

**Comment by LordArcanine** [comment]
/home/wow/azerothcore/modules/mod-account-mounts/src/mod_account_mount.cpp:21:20: fatal error: conversion from 'ObjectGuid' to 'uint32' (aka 'unsigned int') is ambiguous
            uint32 playerGUID = pPlayer->GetGUID();
                   ^            ~~~~~~~~~~~~~~~~~~
/home/wow/azerothcore/src/server/game/Entities/Object/ObjectGuid.h:195:9: note: candidate function
        operator bool() const { return !IsEmpty(); }
        ^
/home/wow/azerothcore/src/server/game/Entities/Object/ObjectGuid.h:239:9: note: candidate function has been explicitly deleted
        operator int64() const = delete;
        ^
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:8957: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-account-mounts/src/mod_account_mount.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1430: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by LordArcanine** [comment]
i think this one works https://github.com/Tyrelis/mod-account-mounts
